# This is the http://travis-ci.org configuration file for Natron
os:
  - linux
  - osx

language: cpp

compiler:
  - gcc
  - clang

# Travis CI has 1.5 cores per VM, take advantage of it
env:
  - CONFIG="coverage debug" MAKEFLAGSPARALLEL="-j 2"

before_script:
  - date -u
  - uname -a
  - tools/travis/install_dependencies.sh

script:
  - git submodule update --init --recursive
  - tools/travis/build.sh

after_success:
  - if [ "$CC" = "gcc" ]; then cd Tests; gcov *.gcno > /dev/null; cd ..; coveralls -n --exclude 'Tests/google-test' --exclude 'Tests/google-mock' --exclude 'libs/OpenFX' --exclude-pattern '.*/moc_.*\.cpp' --exclude-pattern='.*/Tests/.*\.cpp' --exclude-pattern='.*/Tests/.*\.h'; fi
