# This is the http://travis-ci.org configuration file for Natron
os:
  - linux
  - osx

language: cpp

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
      compiler: gcc
  allow_failures:
    - os: osx # we exceed the time limit
  fast_finish: true

cache:
  apt: true
  directories:
  - /usr/local/Cellar

# Travis CI has 1.5 cores per VM, take advantage of it
env:
  - CONFIG="coverage debug" MAKEFLAGSPARALLEL="-j 2"

before_install:
   - date -u
   - uname -a

install:
  - tools/travis/install_dependencies.sh > install_dependencies.log 2>&1

script:
  - tools/travis/build.sh

after_success:
  - if [ "$CC" = "gcc" ]; then cd Tests; gcov *.gcno > /dev/null; cd ..; coveralls -n --exclude 'Tests/google-test' --exclude 'Tests/google-mock' --exclude 'libs/OpenFX' --exclude-pattern '.*/moc_.*\.cpp' --exclude-pattern='.*/Tests/.*\.cpp' --exclude-pattern='.*/Tests/.*\.h'; fi

after_failure:
  - cat install_dependencies.log || true
