# This is the http://travis-ci.org configuration file for Natron
os:
  - linux
  - osx

language: cpp

compiler:
  - gcc
  - clang

before_script:
  - date -u
  - uname -a
  - export J='-j3'
  - tools/travis/install_dependencies.sh

script:
  - git submodule update --init --recursive
  - tools/travis/build.sh

after_success:
  - if [ "$CC" = "gcc" ]; then cd Tests; gcov *.gcno > /dev/null; cd ..; coveralls -n --exclude 'Tests/google-test' --exclude 'Tests/google-mock' --exclude 'libs/OpenFX' --exclude-pattern '.*/moc_.*\.cpp' --exclude-pattern='.*/Tests/.*\.cpp' --exclude-pattern='.*/Tests/.*\.h'; fi
