# This is the http://travis-ci.org configuration file for Natron
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Ss+/N7eLl1cnXRP+XmXuBuuMXTZ/0TUgiGxBJMYGVTmwG2tDDAfhsUh5laeb/OE7dNxwLK5uLeb/XXI4AlP6W7tfquIAAq6/PhKIiRTXDgU6Sfa5voHiM8ni1x9rBtmaOk6/8QjWWSisrQmy9DmxRfYtP2i/sKkpIcJHCs5OCpo="
  # Coverity run condition (avoid matrix multiple runs), need customized
  # build script. Need an update if new matrix cases.
  - coverity_scan_run_condition='"$CC" = gcc -a "$TRAVIS_OS_NAME" != osx'
  # Coverity script test mode (if true no uploading, avoid reaching the quota)
  # usual processing: false.
  - coverity_scan_script_test_mode=false

os:
  - linux
  - osx

language: cpp

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
      compiler: gcc
  allow_failures:
    - os: osx # we exceed the time limit
  fast_finish: true

cache:
  apt: true
  directories:
  - /usr/local/Cellar

# Travis CI has 1.5 cores per VM, take advantage of it
before_install:
   - date -u
   - uname -a
   - export J='-j3'

install:
  - . tools/travis/coverity_env.sh
  - if [[ ${COVERITY_BUILD_DISABLED} == 1 ]];
    then
        exit 0;
    fi
  - tools/travis/install_dependencies.sh > install_dependencies.log 2>&1

script:
  - if [[ ${COVERITY_SCAN_BRANCH} == 1 ]];
    then
      echo "Don't build on coverty_scan branch.";
      exit 0;
    fi
  - tools/travis/build.sh

after_success:
  - if [ "$CC" = "gcc" ]; then cd Tests; gcov *.gcno > /dev/null; cd ..; coveralls -n --exclude 'Tests/google-test' --exclude 'Tests/google-mock' --exclude 'libs/OpenFX' --exclude-pattern '.*/moc_.*\.cpp' --exclude-pattern='.*/Tests/.*\.cpp' --exclude-pattern='.*/Tests/.*\.h'; fi

after_failure:
  - cat install_dependencies.log || true

addons:
  coverity_scan:
    project:
      name: "MrKepzie/Natron"
      description: "Natron Build submitted via Travis CI"
    notification_email: frederic.devernay@inria.fr
    build_command: "tools/travis/build.sh"
    branch_pattern: coverity_scan
