# This is the http://travis-ci.org configuration file for Natron
language: cpp
compiler:
  - gcc
  - clang
# Natron requires boost >= 1.49 to compile in C++11 mode
# see http://stackoverflow.com/questions/11302758/error-while-copy-constructing-boostshared-ptr-using-c11
# we use the irie/boost ppa for that purpose
before_install:
  - git submodule update --init --recursive
  - sudo add-apt-repository -y ppa:irie/boost
  - sudo apt-get update
# Ubuntu 12.04 precise doesn't have a pkg-config file (expat.pc)
install:
  - sudo apt-get install libqt4-dev libglew-dev libboost-serialization-dev libboost-thread-dev libboost-system-dev libexpat1-dev
  - 'echo ''boost: LIBS += -lboost_serialization -lboost_thread -lboost_system'' > config.pri'
  - 'echo ''expat: LIBS += -lexpat'' >> config.pri'
  - 'echo ''expat: PKGCONFIG -= expat'' >> config.pri'
script:
  - if [ "$CC" = "gcc" ]; then qmake CONFIG+=coverage; else qmake -spec unsupported/linux-clang; fi
  - make
